const view=document.getElementById('view'),nav=document.getElementById('chapterNav'),sidebar=document.getElementById('sidebar');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=new Set(JSON.parse(localStorage.getItem('rt-read')||'[]'));
const links=[...chapters.map(c=>({id:c.id,label:c.title,num:c.icon})),{id:'td',label:'Exercices corrigés',num:'TD'},{id:'quiz',label:'Quiz de révision',num:'?'},{id:'flashcards',label:'Flashcards',num:'FC'},{id:'glossaire',label:'Glossaire A–Z',num:'AZ'},{id:'sources',label:'Documents du cours',num:'↗'}];
function renderNav(active){nav.innerHTML=links.map((l,i)=>`${i===chapters.length?'<div class="nav-separator"></div>':''}<a class="nav-item ${l.id===active?'active':''}" href="#${l.id}" ${l.id===active?'aria-current="page"':''}><span class="nav-index">${l.num}</span>${safe(l.label)}</a>`).join('');document.getElementById('progressText').textContent=`${read.size} / ${chapters.length} chapitres lus`;document.getElementById('progressBar').style.width=`${read.size/chapters.length*100}%`}
function shell(eyebrow,title,description,small=false){return `<div class="content"><div class="hero ${small?'hero-small':''}"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>`}
function home(){view.innerHTML=shell('BUT Réseaux & Télécommunications','Réseaux opérateurs<br>& accès','Un parcours de révision à partir des cours, des TD et des fiches techniques fournis. Lis les explications, travaille les questions, puis vérifie tes acquis avec le quiz.')+`<div class="toolbar"><input class="search" id="homeSearch" type="search" placeholder="Chercher un chapitre ou un terme…" aria-label="Chercher un chapitre ou un terme"><a class="button" href="#td">Exercices corrigés</a><a class="button" href="#quiz">Quiz · 60 questions</a><a class="button" href="#flashcards">Flashcards</a><a class="button" href="#glossaire">Acronymes A–Z</a></div><div class="grid" id="chapterGrid">${chapters.map(c=>card(c)).join('')}</div><h2 class="section-title">Méthode pour l’examen</h2><div class="lesson"><p>① Place les équipements sur le trajet. ② Dis à quel niveau tu te trouves : fibre, longueur d’onde, trame OTN, Ethernet, IP ou service. ③ Dans les TD, précise toujours <strong>l’entrée, la sortie et la ressource</strong> (λ, slots, VLAN ou préfixe IP). ④ Vérifie si le flux doit aussi revenir : un trajet monodirectionnel ne suffit pas à un échange bidirectionnel.</p><p class="secondary">Les offres, débits et équipements cités dans les PDF reflètent la date des documents ; ils servent ici à comprendre les exercices.</p></div></div>`;document.getElementById('homeSearch').addEventListener('input',e=>{let q=norm(e.target.value);document.getElementById('chapterGrid').innerHTML=chapters.filter(c=>norm(c.title+' '+c.summary+' '+c.sections.map(s=>s[0]).join(' ')).includes(q)).map(card).join('')||'<p class="empty">Aucun chapitre trouvé. Consulte le glossaire pour chercher un acronyme.</p>'})}
function card(c){return `<a class="card" href="#${c.id}"><span class="number">CHAPITRE ${c.icon} · ${c.group==='op'?'OPÉRATEURS':'ACCÈS'}</span><h3>${safe(c.title)}</h3><p>${safe(c.summary)}</p><span class="arrow">Ouvrir le cours →</span></a>`}
function chapter(c){const index=chapters.indexOf(c);view.innerHTML=shell(`CHAPITRE ${c.icon} · ${c.group==='op'?'RÉSEAU OPÉRATEUR':'RÉSEAU D’ACCÈS'}`,safe(c.title),safe(c.summary),true)+`<p class="crumb"><a href="#vue">← Tous les chapitres</a></p><div class="pill-row">${c.sections.map((s,i)=>`<a class="button" href="#section-${i}" data-jump="${i}">${safe(s[0])}</a>`).join('')}</div>${c.sections.map((s,i)=>`<section class="lesson" id="section-${i}"><h2>${i+1}. ${safe(s[0])}</h2>${s[1]}</section>`).join('')}${exampleMarkup(c)}<div class="source-note">Correspondance : ${safe(c.source)}. <a href="#sources">Ouvrir les documents d’origine</a>.</div><div class="lesson-footer"><button class="button primary" id="markRead">${read.has(c.id)?'✓ Chapitre lu':'Marquer comme lu'}</button><a class="button" href="#${chapters[index+1]?.id||'td'}">${chapters[index+1]?'Chapitre suivant':'Passer aux exercices'} →</a></div></div>`;document.getElementById('markRead').onclick=()=>{read.add(c.id);localStorage.setItem('rt-read',JSON.stringify([...read]));renderNav(c.id);document.getElementById('markRead').textContent='✓ Chapitre lu'};view.querySelectorAll('[data-jump]').forEach(a=>a.onclick=e=>{e.preventDefault();document.getElementById('section-'+a.dataset.jump).scrollIntoView({behavior:'smooth',block:'start'})})}
function td(){let filter='all';view.innerHTML=shell('APPLICATION · TD','Exercices corrigés','Retrouve les questions des TD sous forme de raisonnement guidé. Cherche ta réponse avant d’ouvrir le corrigé.',true)+`<div class="pill-row"><button class="pill active" data-filter="all">Tous</button><button class="pill" data-filter="op">Réseaux opérateurs</button><button class="pill" data-filter="access">Technologies d’accès</button></div><div id="exercises"></div><p class="source-note">Les corrections expliquent une méthode et les hypothèses utiles : les TD demandent parfois un schéma ou des paramètres non fixés par l’énoncé. Les <a href="#sources">PDF originaux</a> restent disponibles.</p></div>`;const fill=()=>{document.getElementById('exercises').innerHTML=exercises.filter(x=>filter==='all'||x.theme===filter).map((x,i)=>`<article class="td-card"><span class="tag ${x.theme==='access'?'amber':''}">${x.theme==='op'?'OPÉRATEURS':'ACCÈS'}</span><h3>${safe(x.title)}</h3><p>${safe(x.question)}</p><details><summary>Afficher le corrigé</summary><div>${safe(x.answer)}</div></details></article>`).join('')};fill();view.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;view.querySelectorAll('[data-filter]').forEach(t=>t.classList.toggle('active',t===b));fill()})}
function norm(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function gloss(){view.innerHTML=shell('RÉFÉRENCE · A–Z','Glossaire des acronymes',`${glossary.length} termes pour décoder le cours et les fiches techniques.`,true)+`<div class="toolbar"><input class="search" id="glossSearch" type="search" placeholder="Ex. ROADM, GEM, DHCP…" aria-label="Rechercher un acronyme"></div><div class="glossary-list" id="glossList"></div></div>`;const fill=()=>{let q=norm(document.getElementById('glossSearch').value);document.getElementById('glossList').innerHTML=glossary.filter(([a,d])=>norm(a+' '+d).includes(q)).map(([a,d])=>`<div class="glossary-row"><strong>${safe(a)}</strong><span>${safe(d)}</span></div>`).join('')||'<div class="empty">Aucun acronyme trouvé.</div>'};fill();document.getElementById('glossSearch').addEventListener('input',fill)}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function exampleMarkup(c){const x=examples.find(x=>x.chapter===c.id);return x?`<section class="lesson worked-example"><span class="tag">EXEMPLE EXPLIQUÉ</span><h2>${safe(x.title)}</h2><p><strong>Situation :</strong> ${safe(x.scenario)}</p><ol>${x.steps.map(t=>`<li>${safe(t)}</li>`).join('')}</ol><div class="tip"><strong>À retenir :</strong> ${safe(x.result)}</div></section>`:''}
function quiz(){
view.innerHTML=shell('AUTOÉVALUATION · '+questions.length+' QUESTIONS','Quiz de révision','Choisis un thème et une longueur de session. Chaque réponse est expliquée, avec un lien vers le chapitre.',true)+`<div class="practice-controls"><label>Thème<select id="quizTheme"><option value="all">Tout le cours</option>${chapters.map(c=>`<option value="${c.id}">${safe(c.title)}</option>`).join('')}</select></label><label>Nombre de questions<select id="quizLength"><option value="10">10 questions</option><option value="20">20 questions</option><option value="all">Toutes les questions du thème</option></select></label><button class="button primary" id="startQuiz">Commencer</button></div><div id="quizStage"><div class="lesson"><h2>Réviser avec les corrections</h2><p>Les questions et les réponses sont mélangées à chaque session. Après ta réponse, lis l’explication puis passe à la suivante. À la fin, tu peux reprendre uniquement les erreurs.</p></div></div></div>`;
const stage=document.getElementById('quizStage');let deck=[],index=0,answers=[],locked=false;
function start(pool){deck=shuffle(pool).map(x=>({...x,choices:shuffle(x.options.map((text,i)=>({text,correct:i===x.correct})))}));index=0;answers=[];show()}
function show(){locked=false;if(index===deck.length){const missed=deck.filter((q,i)=>!answers[i]);stage.innerHTML=`<div class="lesson" aria-live="polite"><span class="eyebrow">SESSION TERMINÉE</span><h2>${deck.length-missed.length} / ${deck.length} bonnes réponses</h2><p>${missed.length?`${missed.length} notion(s) à retravailler. Relis les explications puis réessaie.`:'Toutes les réponses sont correctes. Tu peux changer de thème ou lancer une autre session.'}</p><div class="toolbar">${missed.length?'<button class="button primary" id="retryWrong">Refaire les erreurs</button>':''}<button class="button" id="retryAll">Refaire cette série</button></div></div>`;if(missed.length)document.getElementById('retryWrong').onclick=()=>start(missed);document.getElementById('retryAll').onclick=()=>start(deck);return}
const x=deck[index],chapter=chapters.find(c=>c.id===x.chapter);stage.innerHTML=`<p class="meta">Question ${index+1} / ${deck.length} · ${answers.filter(Boolean).length} bonne(s) réponse(s)</p><article class="quiz-card"><span class="tag">${safe(chapter.title)}</span><h3>${safe(x.q)}</h3><div id="quizChoices">${x.choices.map((o,j)=>`<button class="choice" data-choice="${j}">${safe(o.text)}</button>`).join('')}</div><div id="quizFeedback" aria-live="polite"></div></article>`;
stage.querySelectorAll('.choice').forEach(btn=>btn.onclick=()=>{if(locked)return;locked=true;const choice=x.choices[+btn.dataset.choice];answers.push(choice.correct);stage.querySelectorAll('.choice').forEach((b,j)=>{b.disabled=true;if(x.choices[j].correct)b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});document.getElementById('quizFeedback').innerHTML=`<div class="feedback"><strong>${choice.correct?'Bonne réponse.':'À revoir.'}</strong> ${safe(x.why)}<p><a href="#${x.chapter}">Relire le chapitre</a></p></div><button class="button primary" id="nextQuiz">${index+1===deck.length?'Voir le résultat':'Question suivante →'}</button>`;document.getElementById('nextQuiz').onclick=()=>{index++;show()}})}
document.getElementById('startQuiz').onclick=()=>{const theme=document.getElementById('quizTheme').value;let pool=questions.filter(q=>theme==='all'||q.chapter===theme);const count=document.getElementById('quizLength').value;if(count!=='all')pool=shuffle(pool).slice(0,+count);start(pool)};
}
function flash(){
let known;try{known=new Set(JSON.parse(localStorage.getItem('rt-known-cards')||'[]'))}catch{known=new Set()}
let deck=[],index=0,flipped=false;
view.innerHTML=shell('MÉMORISATION · '+flashcards.length+' CARTES','Flashcards','Essaie de répondre avant de retourner la carte. Tes cartes connues sont mémorisées sur cet appareil.',true)+`<div class="practice-controls"><label>Thème<select id="flashTheme"><option value="all">Toutes les cartes</option>${[...new Set(flashcards.map(c=>c.group))].map(g=>`<option>${safe(g)}</option>`).join('')}</select></label><label class="check-label"><input type="checkbox" id="reviewOnly"> Uniquement à revoir</label><button class="button" id="shuffleCards">Mélanger</button></div><p class="meta" id="flashCount" aria-live="polite"></p><div id="flashStage"></div></div>`;
const stage=document.getElementById('flashStage');
function filter(){const group=document.getElementById('flashTheme').value;const review=document.getElementById('reviewOnly').checked;deck=flashcards.filter(c=>(group==='all'||c.group===group)&&(!review||!known.has(c.id)));index=0;flipped=false;render()}
function render(){document.getElementById('flashCount').textContent=`${known.size} / ${flashcards.length} cartes connues · ${deck.length?`carte ${index+1} / ${deck.length}`:'aucune carte à revoir dans cette sélection'}`;if(!deck.length){stage.innerHTML='<div class="lesson"><h2>Sélection terminée</h2><p>Change de thème ou désactive « Uniquement à revoir » pour continuer.</p></div>';return}const c=deck[index];stage.innerHTML=`<button class="flashcard ${flipped?'revealed':''}" id="flipCard" aria-label="${flipped?'Afficher la question':'Afficher la réponse'}"><span class="tag">${safe(c.group)}${known.has(c.id)?' · Connue':''}</span><span class="flash-side">${flipped?'RÉPONSE':'QUESTION'}</span><span class="flash-text">${safe(flipped?c.a:c.q)}</span><span class="flash-hint">${flipped?'Clique pour revoir la question':'Clique ou appuie sur Entrée pour retourner'}</span></button><div class="flash-actions"><button class="button" id="prevCard" ${index===0?'disabled':''}>← Précédente</button><button class="button" id="reviewCard" ${!flipped?'disabled':''}>À revoir</button><button class="button primary" id="knownCard" ${!flipped?'disabled':''}>Je sais</button><button class="button" id="nextCard" ${index===deck.length-1?'disabled':''}>Suivante →</button></div>`;
document.getElementById('flipCard').onclick=()=>{flipped=!flipped;render();document.getElementById('flipCard').focus()};document.getElementById('prevCard').onclick=()=>{if(index>0)index--;flipped=false;render()};document.getElementById('nextCard').onclick=()=>{if(index<deck.length-1)index++;flipped=false;render()};
function mark(value){if(value)known.add(c.id);else known.delete(c.id);try{localStorage.setItem('rt-known-cards',JSON.stringify([...known]))}catch{}if(value&&document.getElementById('reviewOnly').checked){deck.splice(index,1);index=Math.min(index,Math.max(0,deck.length-1))}else if(index<deck.length-1)index++;flipped=false;render()}
document.getElementById('knownCard').onclick=()=>mark(true);document.getElementById('reviewCard').onclick=()=>mark(false)}
document.getElementById('flashTheme').onchange=filter;document.getElementById('reviewOnly').onchange=filter;document.getElementById('shuffleCards').onclick=()=>{deck=shuffle(deck);index=0;flipped=false;render()};filter();
}

function sources(){view.innerHTML=shell('DOCUMENTATION','Documents d’origine','Les cours, énoncés de TD et fiches techniques consultés pour construire ce site.',true)+`<div class="resource-list">${resources.map(([n,p])=>`<a class="resource" href="${p}" target="_blank" rel="noopener"><span>${safe(n)}</span><span>PDF ↗</span></a>`).join('')}</div><div class="source-note">Les passages du cours sont reformulés et complétés pour la révision. Les dates des fichiers peuvent rendre certaines descriptions commerciales ou techniques historiques.</div></div>`}
function route(){let id=decodeURIComponent(location.hash.slice(1))||'vue';let c=chapters.find(c=>c.id===id);if(c)chapter(c);else if(id==='td')td();else if(id==='quiz')quiz();else if(id==='flashcards')flash();else if(id==='glossaire')gloss();else if(id==='sources')sources();else{id='vue';home()}renderNav(id);sidebar.classList.remove('open');document.getElementById('mobileNav').setAttribute('aria-expanded','false');window.scrollTo(0,0)}
document.getElementById('mobileNav').onclick=()=>{let opened=sidebar.classList.toggle('open');document.getElementById('mobileNav').setAttribute('aria-expanded',String(opened))};window.addEventListener('hashchange',route);route();
